### GET /payment api
GET http://localhost:3000/api/payment
X-ACCESS-TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNTk2NTE2Mjc0fQ.JHzCy3wzRMf2G1A2gPfQ4f64qtSBC6BADV0NhIePbLk

### POST /payment api
POST http://localhost:3000/api/payment
Content-Type: application/json
Cookie: username=coldbrew

{
    "payment_name": "배민뱅크"
}

### DELETE /payment api  
DELETE  http://localhost:3000/api/payment/41